version: '3.5'

services:

  db:
    image: mariadb:latest
    restart: always
    env_file: .env
#    environment:
#      - MARIADB_ROOT_PASSWORD=XXXXXX
    ports:
      - 3306:3306
    volumes:
      - mariadb:/var/lib/mysql
    logging:
      driver: none

  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_HOST=db
      - UPLOAD_LIMIT=2G
      - MEMORY_LIMIT=2048M
      - MAX_EXECUTION_TIME=900
    logging:
      driver: none

volumes:
  mariadb:
